# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. 
# The "2" in Vagrant.configure configures the configuration version.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
end
